# Generated by Django 5.2.4 on 2025-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
