# Generated by Django 5.2.4 on 2025-07-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mission_images/')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.mission')),
            ],
        ),
    ]
